genernal:
  label: 基本设置
  items:
    index_notice:
      name: index_notice
      label: 首页公告
      type: textarea
      default: 'Yimolan正在开发中ing...'
    github:
      name: github               
      label: github              
      type: text                
      placeholder: 'github个人主页链接'       
    email:
      name: email               
      label: 邮箱              
      type: text                
      placeholder: '个人邮箱'      
    record:
      name: record
      label: 备案号
      type: text
      placeholder: '填写备案号'


style:
  label: 样式设置
  items:
    mdui_theme:
      name: mdui_theme
      label: 主题色
      type: select
      default: 'mdui-theme-primary-blue'
      options:
        - value: 'mdui-theme-primary-blue'
          label: '宝石蓝'
        - value: 'mdui-theme-primary-green'
          label: '原谅绿'
        - value: 'mdui-theme-primary-red'
          label: '姨妈红'
        - value: 'mdui-theme-primary-pink'
          label: '少女粉'
        - value: 'mdui-theme-primary-purple'
          label: '基佬紫'
        - value: 'mdui-theme-primary-orange'
          label: '大橘观'
        - value: 'mdui-theme-primary-blue-grey'
          label: '萧条灰'
        - value: 'mdui-theme-primary-brown'
          label: '低调棕'
        - value: 'mdui-theme-primary-cyan'
          label: '靛蓝青'
    indeximg:
      name: indeximg               
      label: 镇站图              
      type: attachment               
      placeholder: '图片地址'           
      default: ''               